name: Unzip Project

on:
  push:
    paths:
      - "**.zip"

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip
        run: |
          unzip -o *.zip
          rm *.zip

      - name: Commit extracted files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Extract ZIP"
          git push
